config/routes.rb
Rails.application.routes.draw do
  get "sessions/login", to: "sessions#login", as: :login
  get "sessions/register", to: "sessions#register", as: :register
  get "sessions/receive-login", to: "sessions#receive_login", as: :receive_login
  post "sessions/save-login", to: "sessions#save_login", as: :save_login
  delete "sessions/logout", to: "sessions#logout", as: :logout
  resources :exercises
  resources :exercise_sets, path: "sets"
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "exercise_sets#index"
end

app/models/exercise_set.rb
class ExerciseSet < ApplicationRecord
  belongs_to :user
  has_many :exercises, dependent: :destroy

  validates :name, presence: true, uniqueness: { case_sensitive: false, scope: :user_id }

  def to_s
    name
  end
end

app/controllers/exercise_sets_controller.rb
class ExerciseSetsController < ApplicationController
  before_action :registered_only, only: %i[create update destroy]
  before_action :set_exercise_set, only: %i[show edit update destroy]

  # GET /exercise_sets
  # GET /exercise_sets.json
  def index
    @exercise_sets = ExerciseSet.all
  end

  # GET /exercise_sets/1
  # GET /exercise_sets/1.json
  def show
  end

  # GET /exercise_sets/new
  def new
    @exercise_set = ExerciseSet.new
  end

  # GET /exercise_sets/1/edit
  def edit
  end

  # POST /exercise_sets
  # POST /exercise_sets.json
  def create
    @exercise_set = ExerciseSet.new(exercise_set_params)

    respond_to do |format|
      if @exercise_set.save
        format.html { redirect_to @exercise_set, notice: "Exercise set was successfully created." }
        format.json { render :show, status: :created, location: @exercise_set }
      else
        format.html { render :new }
        format.json { render json: @exercise_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercise_sets/1
  # PATCH/PUT /exercise_sets/1.json
  def update
    respond_to do |format|
      if @exercise_set.update(exercise_set_params)
        format.html { redirect_to @exercise_set, notice: "Exercise set was successfully updated." }
        format.json { render :show, status: :ok, location: @exercise_set }
      else
        format.html { render :edit }
        format.json { render json: @exercise_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercise_sets/1
  # DELETE /exercise_sets/1.json
  def destroy
    @exercise_set.destroy
    respond_to do |format|
      format.html { redirect_to exercise_sets_url, notice: "Exercise set was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_exercise_set
      @exercise_set = ExerciseSet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exercise_set_params
      params.require(:exercise_set).permit(:name, :description, :user_id)
    end
end

app/views/exercise_sets/_form.html.slim
= form_for @exercise_set do |f|
  - if @exercise_set.errors.any?
    #error_explanation
      h2 = "#{pluralize(@exercise_set.errors.count, "error")} prohibited this exercise_set from being saved:"
      ul
        - @exercise_set.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :user
    = f.text_field :user
  .actions = f.submit

app/views/exercise_sets/edit.html.slim
h1 Editing exercise_set

== render 'form'

=> link_to 'Show', @exercise_set
'|
=< link_to 'Back', exercise_sets_path

app/views/exercise_sets/index.html.slim
h1 Listing exercise_sets

table.table
  thead
    tr
      th Name
      th Description
      th User
      th
      th

  tbody
    - @exercise_sets.each do |exercise_set|
      tr
        td = link_to exercise_set.name, exercise_set
        td = exercise_set.description
        td = exercise_set.user
        td = link_to 'Edit', edit_exercise_set_path(exercise_set)
        td = link_to 'Delete', exercise_set, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Exercise set', new_exercise_set_path

app/views/exercise_sets/new.html.slim
h1 New exercise_set

== render 'form'

= link_to 'Back', exercise_sets_path

app/views/exercise_sets/show.html.slim
- exercises = @exercise_set.exercises.order(:position)
h1.title= @exercise_set.name
p.subtitle By #{@exercise_set.user}

= @exercise_set.description

.columns
  .column
    button.button.is-success#start Start
    button.button.is-warning#pause Pause
    section.section
      #runner data-exercises=exercises.to_json
  .column
    table
      thead
        tr
          th Name

      tbody
        - exercises.each do |exercise|
          tr
            td = exercise.name

audio#tick-sound
  source src="/metronome.mp3" type="audio/mpeg"

audio#switch
  source src="/switch.mp3" type="audio/mpeg"