config/routes.rb
Rails.application.routes.draw do
  get "sessions/login", to: "sessions#login", as: :login
  get "sessions/register", to: "sessions#register", as: :register
  get "sessions/receive-login", to: "sessions#receive_login", as: :receive_login
  post "sessions/save-login", to: "sessions#save_login", as: :save_login
  delete "sessions/logout", to: "sessions#logout", as: :logout
  resources :exercises
  resources :exercise_sets, path: "sets"
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "exercise_sets#index"
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :registered_only, only: %i[create update destroy]
  before_action :set_exercise, only: %i[show edit update destroy]

  # GET /exercises
  # GET /exercises.json
  def index
    @exercises = Exercise.all
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
  end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = Exercise.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: "Exercise was successfully created." }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1
  # PATCH/PUT /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to @exercise, notice: "Exercise was successfully updated." }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise.destroy
    respond_to do |format|
      format.html { redirect_to exercises_url, notice: "Exercise was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exercise_params
      params.require(:exercise).permit(:exercise_set_id, :name, :description, :duration, :position, :rest)
    end
end

app/views/exercises/_form.html.slim
= form_for @exercise do |f|
  - if @exercise.errors.any?
    #error_explanation
      h2 = "#{pluralize(@exercise.errors.count, "error")} prohibited this exercise from being saved:"
      ul
        - @exercise.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :exercise_set
    = f.text_field :exercise_set
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :duration
    = f.number_field :duration
  .field
    = f.label :position
    = f.number_field :position
  .field
    = f.label :rest
    = f.number_field :rest
  .actions = f.submit

app/views/exercises/edit.html.slim
h1 Editing exercise

== render 'form'

=> link_to 'Show', @exercise
'|
=< link_to 'Back', exercises_path

app/views/exercises/index.html.slim
h1 Listing exercises

table
  thead
    tr
      th Exercise set
      th Name
      th Description
      th Duration
      th Position
      th Rest
      th
      th
      th

  tbody
    - @exercises.each do |exercise|
      tr
        td = exercise.exercise_set
        td = exercise.name
        td = exercise.description
        td = exercise.duration
        td = exercise.position
        td = exercise.rest
        td = link_to 'Show', exercise
        td = link_to 'Edit', edit_exercise_path(exercise)
        td = link_to 'Destroy', exercise, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Exercise', new_exercise_path

app/views/exercises/new.html.slim
h1 New exercise

== render 'form'

= link_to 'Back', exercises_path

app/views/exercises/show.html.slim
p#notice = notice

p
  strong Exercise set:
  = @exercise.exercise_set
p
  strong Name:
  = @exercise.name
p
  strong Description:
  = @exercise.description
p
  strong Duration:
  = @exercise.duration
p
  strong Position:
  = @exercise.position
p
  strong Rest:
  = @exercise.rest

=> link_to 'Edit', edit_exercise_path(@exercise)
'|
=< link_to 'Back', exercises_path