config/routes.rb
Rails.application.routes.draw do
  get "sessions/login", to: "sessions#login", as: :login
  get "sessions/register", to: "sessions#register", as: :register
  get "sessions/receive-login", to: "sessions#receive_login", as: :receive_login
  post "sessions/save-login", to: "sessions#save_login", as: :save_login
  delete "sessions/logout", to: "sessions#logout", as: :logout
  resources :exercises
  resources :exercise_sets, path: "sets"
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "exercise_sets#index"
end

app/views/layouts/_flash.html.slim
.row
  .col-sm
    .flash
      - flash.each do |key, val|
        .alert.alert-warning.alert-dismissible.fade.show role=alert
          = val
          button.close type="button" data-dismiss="alert" aria-label="Close"
            span aria-hidden="true" &times;

app/views/layouts/_nav.html.slim
nav.level.is-mobile
  p.level-item.has-text-centered
    = link_to "Sets", exercise_sets_path, class: "link is-info"
  p.level-item.has-text-centered
    = link_to "Users", users_path, class: "link is-info"
  - if current_user
    p.level-item.has-text-centered
      = link_to "Logged in as #{current_user.username}", users_path(current_user), class: "link is-info"
    p.level-item.has-text-centered
      = link_to "Log Out", logout_path, class: "link is-info", method: :delete
  - else
    p.level-item.has-text-centered
      = link_to "Log In", login_path, class: "link is-info"
    p.level-item.has-text-centered
      = link_to "Register", register_path, class: "link is-info"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Workout</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <%= stylesheet_link_tag    'application', media: 'all' %>
    </head>

    <body>
        <section class="section">
            <div class="container">
                <%= render "layouts/nav" %>
                <%= render "layouts/flash" %>
                <%= yield %>
            </div>
        </section>
        <%= javascript_include_tag 'application' %>
    </body>
</html>